# DATA GATHERING

In [1]:
import pandas as pd
import numpy as np

### Import data from CSV Files

In [2]:
#opening a local csv file:

df = pd.read_csv('datasets/batter.csv')
df.sample(5)

              batter  runs        avg  strike_rate
271          MS Gony    99   9.900000   130.263158
345      D Pretorius    44  11.000000   157.142857
555       KP Appanna     2   2.000000    50.000000
522  Aman Hakim Khan     5   5.000000   166.666667
86         A Symonds   974  36.074074   124.711908

In [3]:
#opening a csv file from url:

import requests
from io import StringIO

url = 'https://raw.githubusercontent.com/amrsaeedhosny/countries/main/countries.csv'
req = requests.get(url)
data = StringIO(req.text)

pd.read_csv(data)

          English Name      Arabic Name Alpha-2 Code Alpha-3 Code  Phone Code
0          Afghanistan        أفغانستان           AF          AFG          93
1        Åland Islands       جزر أولاند           AX          ALA         358
2              Albania          ألبانيا           AL          ALB         355
3              Algeria          الجزائر           DZ          DZA         213
4       American Samoa  ساموا الأمريكية           AS          ASM         684
..                 ...              ...          ...          ...         ...
245  Wallis and Futuna    واليس وفوتونا           WF          WLF         681
246     Western Sahara  الصحراء الغربية           EH          ESH         212
247              Yemen            اليمن           YE          YEM         967
248             Zambia           زامبيا           ZM          ZMB         260
249           Zimbabwe         زيمبابوي           ZW          ZWE         263

[250 rows x 5 columns]

In [4]:
#or pandas can directly read from url:

url = 'https://raw.githubusercontent.com/amrsaeedhosny/countries/main/countries.csv'

df = pd.read_csv(url)
df.head()

     English Name      Arabic Name Alpha-2 Code Alpha-3 Code  Phone Code
0     Afghanistan        أفغانستان           AF          AFG          93
1   Åland Islands       جزر أولاند           AX          ALA         358
2         Albania          ألبانيا           AL          ALB         355
3         Algeria          الجزائر           DZ          DZA         213
4  American Samoa  ساموا الأمريكية           AS          ASM         684

In [12]:
#tsv file dataset (sep parameter):

tsv = pd.read_csv('datasets/Employee Dataset - TSV.txt', sep='\t')
tsv

,Employee Name,Age,Last Working Day,Department,Education,Gender,Marital Status,Monthly Income,Years of Experience,Percent Salary Hike,Performance Rating
0,Jitesh,41,31-12-9999,Training,Masters,Male,Single,5993,8,11,3
1,Sanjit,49,31-12-9999,Sales,Masters,Male,Married,5130,1,23,4
2,John,37,31-12-9999,R&D,Doctorate,Male,Single,2090,6,15,3
3,Sandra,33,31-12-9999,Software Development,Undergraduate,Female,Married,2909,1,11,3
4,Madhu,27,31-12-9999,R&D,Masters,Male,Married,3468,9,12,3
5,Robert,32,31-12-9999,R&D,Masters,Male,Single,3068,0,13,3
6,Megan,59,31-12-9999,Software Development,Masters,Female,Married,2670,4,20,4
7,Matt,30,31-12-9999,R&D,Doctorate,Male,Divorced,2693,1,22,4
8,Will,38,01-03-2012,R&D,Doctorate,Male,Single,9526,0,21,4
9,George,36,31-12-9999,Software Development,Masters,NaN,Married,5237,6,13,3
10,Adam,35,31-12-9999,Software Development,Masters,Male,Married,2426,0,13,3
11,Adam,35,31-12-9999,Software Development,Masters,Male,Married,2426,0,13,3
12,Adam,35,31-12-9999,Software Development,Masters,Male,Married,2426,0,13,3
13,Emma,29,31-12-9999,Software Development,Undergraduate,Female,Single,4193,0,12,3
14,Vin,31,31-12-9999,Software Development,Undergraduate,Male,NaN,2911,1,17,3
15,Richard,34,31-12-9999,Software Development,Undergraduate,Male,Divorced,2661,0,11,3
16,Clint,28,31-12-9999,Software Development,Undergraduate,Male,Single,2028,5,14,3
17,Kate,29,31-12-9999,Software Development,Undergraduate,Female,NaN,9980,1,11,3
18,Morgan,32,31-12-9999,Software Development,Undergraduate,Male,Divorced,3298,0,12,3
19,Mel,22,01-06-2014,Software Development,Masters,Male,Divorced,2935,1,13,3
20,Nicole,53,31-12-9999,Sales,Masters,Female,Married,15427,2,16,3
21,Angelina,38,31-12-9999,R&D,Doctorate,Female,Single,3944,5,11,3
22,Katherine,24,31-12-9999,Development,Masters,Female,Divorced,4011,0,18,3
23,Sean,36,31-12-9999,Sales,Masters,Male,Single,3407,7,23,4
24,Stella,34,31-12-9999,R&D,Doctorate,Female,Single,11994,0,11,3

In [19]:
vk = pd.read_csv('datasets/vk.csv')
vk

     match_id  batsman_runs
0          12            62
1          17            28
2          20            64
3          27             0
4          30            10
..        ...           ...
136       624            75
137       626           113
138       632            54
139       633             0
140       636            54

[141 rows x 2 columns]

In [ ]:
#Index_col parameter:

vk = pd.read_csv('datasets/vk.csv', index_col='match_id')
vk

          batsman_runs
match_id
12                  62
17                  28
20                  64
27                   0
30                  10
...                ...
624                 75
626                113
632                 54
633                  0
636                 54

[141 rows x 1 columns]