# DATA GATHERING

In [1]:
import pandas as pd
import numpy as np

### Import data from CSV Files

In [5]:
#opening a local csv file:

df = pd.read_csv('datasets/batter.csv')
df.sample(5)

               batter  runs        avg  strike_rate
569           MA Wood     1   1.000000    20.000000
519           A Zampa     5   2.500000    62.500000
431  Y Gnaneswara Rao    19  19.000000   105.555556
351           A Nehra    41   5.857143    65.079365
360          Umar Gul    39  13.000000   205.263158

In [11]:
#opening a csv file from url:

import requests
from io import StringIO

url = 'https://raw.githubusercontent.com/amrsaeedhosny/countries/main/countries.csv'
req = requests.get(url)
data = StringIO(req.text)

pd.read_csv(data)

          English Name      Arabic Name Alpha-2 Code Alpha-3 Code  Phone Code
0          Afghanistan        أفغانستان           AF          AFG          93
1        Åland Islands       جزر أولاند           AX          ALA         358
2              Albania          ألبانيا           AL          ALB         355
3              Algeria          الجزائر           DZ          DZA         213
4       American Samoa  ساموا الأمريكية           AS          ASM         684
..                 ...              ...          ...          ...         ...
245  Wallis and Futuna    واليس وفوتونا           WF          WLF         681
246     Western Sahara  الصحراء الغربية           EH          ESH         212
247              Yemen            اليمن           YE          YEM         967
248             Zambia           زامبيا           ZM          ZMB         260
249           Zimbabwe         زيمبابوي           ZW          ZWE         263

[250 rows x 5 columns]